# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_model',
            name='image',
            field=models.ImageField(upload_to=b'/my-media'),
        ),
    ]
