# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160627_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_east',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to=b'east')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='api_north',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to=b'north')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='api_south',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to=b'south')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='api_west',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to=b'west')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='api_model',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='api_model',
            name='image',
            field=models.ImageField(upload_to=b'my-media'),
        ),
    ]
