# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160710_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
