from . import views
from django.conf.urls import url

urlpatterns = [
	url('^register/$', views.register, name="register"),
	url(r'^$', views.home_page),
	url(r'^home/', views.index1),
	url('^register-api/', views.register_api),
	url(r'^android-api/', views.android_api),
	url(r'^android-api-volley/', views.android_api_volley),
	url(r'^android-api1/', views.android_api1),
	url(r'^api-north/', views.api_north1),
	url(r'^api-south/', views.api_south1),
	url(r'^api-east/', views.api_east1),
	url(r'^api-west/', views.api_west1),
	url(r'^api-a/', views.api_a1),
	url(r'^api-b/', views.api_b1),
	url(r'^api-c/', views.api_c1),
	url(r'^api-d/', views.api_d1),
	url(r'^api-north-volley/', views.api_north1_volley),
	url(r'^api-south-volley/', views.api_south1_volley),
	url(r'^api-east-volley/', views.api_east1_volley),
	url(r'^api-west-volley/', views.api_west1_volley),
	url(r'^api-a-volley/', views.api_a1_volley),
	url(r'^api-b-volley/', views.api_b1_volley),
	url(r'^api-c-volley/', views.api_c1_volley),
	url(r'^api-d-volley/', views.api_d1_volley),
	url(r'^api-search/', views.search1),
	url(r'^api-search-volley/', views.search1_volley),
	# url(r'^xyz/(?P<para>\w+)/', views.search),
]
